dist: trusty
language: cpp

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install --yes qt5-default qttools5-dev-tools
 
script:
    - qmake -qt=qt5 d2d.pro
    - make

